import Navbar from "@/layout/navbar/navbar"
import Footer from "@/layout/footer"
import Head from "next/head"

const BaseLayout = ({children}) => {
  return (
    <>
    <Head>
      <title>Travjoy</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo2.png" />
    </Head>
    <main>
      <Navbar/>
      <div>
       {children}
      </div>
      <Footer/>
    </main>
    </>
  )
}

export default BaseLayout
